### ISSUE TITLE
Initialize / Uninitialize race condition

### ISSUE THREAD

**Issue by yalegko** [scjalliance/comshim#1]
**Actual**:  `comshim` has a race between `ole.CoUninitialize` and following `ole.CoInitializeEx`

**Expected**: `comshim.Add` and `comshim.Done` can be safely invoked from independent goroutines

**Proposal**:  Looks like we need some kind of synchronization between subsequent stops & starts. 

Moving `defer ole.CoUninitialize()` from [L103](https://github.com/scjalliance/comshim/blob/master/shim.go#L103) to `ole.CoUninitialize()` in the synchronized code block (before `s.m.Unlock()` on [L112](https://github.com/scjalliance/comshim/blob/master/shim.go#L112)  (which seems reasonable place for it) makes the issue not reproducible (at least by me). 

But I'm not sure that it was a reason and not just a small time lag in a right place. So hope you could also take a look at the code and give a fix or advice.

**Reproduce** 
```golang
package main

import (
	"fmt"
	"github.com/go-ole/go-ole/oleutil"
	"github.com/scjalliance/comshim"
	"runtime"
	"sync"
)

func main() {
	// Ensure we have enough threads (10 is totally empirical).
	runtime.GOMAXPROCS(10)

	// Do some COM interaction that leads to ole.CoInitialize + ole.CoUninitialize
	// calls.
	comshim.Add(1)
	_, err := oleutil.CreateObject("WbemScripting.SWbemLocator")
	if err != nil {
		fmt.Println(err)
	}
	comshim.Done()

	// And now try to call `comshim.Add` and do any `COM` call with
	// minimal delay between them.
	wg := sync.WaitGroup{}
	for i := 0; i < 101; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			comshim.Add(1)
			defer comshim.Done()
			_, err := oleutil.CreateObject("WbemScripting.SWbemLocator")
			if err != nil {
				fmt.Println(i, err)
			}
		}(i)
	}
	wg.Wait()
}
```

From launch to launch it can accidentally print something like 
```
100 Object server is stopping when OLE service contacts it
```

**Comment by JoshuaSjoding** [comment]
Good catch! You are absolutely right, the `CoUninitialize()` call needed to happen within the write lock.

It should be fixed now.

**Comment by yalegko** [comment]
Shouldn't we be able to catch `S_FALSE` in `ole.CoInitializeEx` return in an assumption that second `ole.CoInitializeEx` happens before `ole.CoUninitialize`?

I didn't do that fix by myself cos I wasn't able to catch it, so wasn't sure that it's a place with race. 

But If you also think this was a problem place, I think we can close the issue until it appear again 😄

**Comment by JoshuaSjoding** [comment]
I modified `shim.run()` so that it panics if it ends up on a thread that was already initialized, as indicated by `CoInitializeEx()` returning `S_FALSE `. If that ever happens it's an indication that there's a bug or a race condition somewhere else.

I think the race condition has been fixed so I'm going to close this. If you find evidence to the contrary let us know.

Thanks again!
